runtime: go
api_version: go1

handlers:

## trial saveg
## Command to run is dev_appserver.py   --enable_console=1 --log_level=debug  --support_datastore_emulator=true  --clear_datastore=yes app.yaml

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$
##  static_files: favicon.ico
  #upload: favicon\.ico

- url: /static
  static_dir: static

# All URLs are handled by the Go application script this order is last as it will overwrite static if first
- url: /.*
  script: _go_app
